//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SirenaSoapClient.SirenaGateServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SirenaGateServiceReference.ISirenaGateService")]
    public interface ISirenaGateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendStringRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendStringRequestResponse")]
        string SendStringRequest(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendStringRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendStringRequestResponse")]
        System.Threading.Tasks.Task<string> SendStringRequestAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/StringRequest", ReplyAction="http://tempuri.org/ISirenaGateService/StringRequestResponse")]
        string StringRequest(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/StringRequest", ReplyAction="http://tempuri.org/ISirenaGateService/StringRequestResponse")]
        System.Threading.Tasks.Task<string> StringRequestAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/KeyInfoRequest", ReplyAction="http://tempuri.org/ISirenaGateService/KeyInfoRequestResponse")]
        Sirena.KeyInfoResponse KeyInfoRequest([System.ServiceModel.MessageParameterAttribute(Name="keyInfoRequest")] Sirena.KeyInfoRequest keyInfoRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/KeyInfoRequest", ReplyAction="http://tempuri.org/ISirenaGateService/KeyInfoRequestResponse")]
        System.Threading.Tasks.Task<Sirena.KeyInfoResponse> KeyInfoRequestAsync(Sirena.KeyInfoRequest keyInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendKeyInfoRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendKeyInfoRequestResponse")]
        Sirena.KeyInfoResponse SendKeyInfoRequest(Sirena.KeyInfoRequest keyInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendKeyInfoRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendKeyInfoRequestResponse")]
        System.Threading.Tasks.Task<Sirena.KeyInfoResponse> SendKeyInfoRequestAsync(Sirena.KeyInfoRequest keyInfoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/ScheduleRequest", ReplyAction="http://tempuri.org/ISirenaGateService/ScheduleRequestResponse")]
        Sirena.ScheduleResponse ScheduleRequest([System.ServiceModel.MessageParameterAttribute(Name="scheduleRequest")] Sirena.ScheduleRequest scheduleRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/ScheduleRequest", ReplyAction="http://tempuri.org/ISirenaGateService/ScheduleRequestResponse")]
        System.Threading.Tasks.Task<Sirena.ScheduleResponse> ScheduleRequestAsync(Sirena.ScheduleRequest scheduleRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendScheduleRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendScheduleRequestResponse")]
        Sirena.ScheduleResponse SendScheduleRequest(Sirena.ScheduleRequest scheduleRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendScheduleRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendScheduleRequestResponse")]
        System.Threading.Tasks.Task<Sirena.ScheduleResponse> SendScheduleRequestAsync(Sirena.ScheduleRequest scheduleRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/AvailabilityRequest", ReplyAction="http://tempuri.org/ISirenaGateService/AvailabilityRequestResponse")]
        Sirena.AvailabilityResponse AvailabilityRequest([System.ServiceModel.MessageParameterAttribute(Name="availabilityRequest")] Sirena.AvailabilityRequest availabilityRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/AvailabilityRequest", ReplyAction="http://tempuri.org/ISirenaGateService/AvailabilityRequestResponse")]
        System.Threading.Tasks.Task<Sirena.AvailabilityResponse> AvailabilityRequestAsync(Sirena.AvailabilityRequest availabilityRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendAvailabilityRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendAvailabilityRequestResponse")]
        Sirena.AvailabilityResponse SendAvailabilityRequest(Sirena.AvailabilityRequest availabilityRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendAvailabilityRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendAvailabilityRequestResponse")]
        System.Threading.Tasks.Task<Sirena.AvailabilityResponse> SendAvailabilityRequestAsync(Sirena.AvailabilityRequest availabilityRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/FaresRequest", ReplyAction="http://tempuri.org/ISirenaGateService/FaresRequestResponse")]
        Sirena.FaresResponse FaresRequest([System.ServiceModel.MessageParameterAttribute(Name="faresRequest")] Sirena.FaresRequest faresRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/FaresRequest", ReplyAction="http://tempuri.org/ISirenaGateService/FaresRequestResponse")]
        System.Threading.Tasks.Task<Sirena.FaresResponse> FaresRequestAsync(Sirena.FaresRequest faresRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendFaresRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendFaresRequestResponse")]
        Sirena.FaresResponse SendFaresRequest(Sirena.FaresRequest faresRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendFaresRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendFaresRequestResponse")]
        System.Threading.Tasks.Task<Sirena.FaresResponse> SendFaresRequestAsync(Sirena.FaresRequest faresRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/FareremarkRequest", ReplyAction="http://tempuri.org/ISirenaGateService/FareremarkRequestResponse")]
        Sirena.FareremarkResponse FareremarkRequest([System.ServiceModel.MessageParameterAttribute(Name="fareremarkRequest")] Sirena.FareremarkRequest fareremarkRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/FareremarkRequest", ReplyAction="http://tempuri.org/ISirenaGateService/FareremarkRequestResponse")]
        System.Threading.Tasks.Task<Sirena.FareremarkResponse> FareremarkRequestAsync(Sirena.FareremarkRequest fareremarkRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendFareremarkRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendFareremarkRequestResponse")]
        Sirena.FareremarkResponse SendFareremarkRequest(Sirena.FareremarkRequest fareremarkRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendFareremarkRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendFareremarkRequestResponse")]
        System.Threading.Tasks.Task<Sirena.FareremarkResponse> SendFareremarkRequestAsync(Sirena.FareremarkRequest fareremarkRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PricingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PricingRequestResponse")]
        Sirena.Dto.Responses.PricingResponse PricingRequest([System.ServiceModel.MessageParameterAttribute(Name="pricingRequest")] Sirena.Dto.Requests.PricingRequest pricingRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PricingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PricingRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PricingResponse> PricingRequestAsync(Sirena.Dto.Requests.PricingRequest pricingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPricingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPricingRequestResponse")]
        Sirena.Dto.Responses.PricingResponse SendPricingRequest(Sirena.Dto.Requests.PricingRequest pricingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPricingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPricingRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PricingResponse> SendPricingRequestAsync(Sirena.Dto.Requests.PricingRequest pricingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/DescribeRequest", ReplyAction="http://tempuri.org/ISirenaGateService/DescribeRequestResponse")]
        Sirena.Dto.Responses.DescribeResponse DescribeRequest([System.ServiceModel.MessageParameterAttribute(Name="describeRequest")] Sirena.Dto.Requests.DescribeRequest describeRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/DescribeRequest", ReplyAction="http://tempuri.org/ISirenaGateService/DescribeRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.DescribeResponse> DescribeRequestAsync(Sirena.Dto.Requests.DescribeRequest describeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendDescribeRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendDescribeRequestResponse")]
        Sirena.Dto.Responses.DescribeResponse SendDescribeRequest(Sirena.Dto.Requests.DescribeRequest describeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendDescribeRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendDescribeRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.DescribeResponse> SendDescribeRequestAsync(Sirena.Dto.Requests.DescribeRequest describeRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/BookingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/BookingRequestResponse")]
        Sirena.BookingResponse BookingRequest([System.ServiceModel.MessageParameterAttribute(Name="bookingRequest")] Sirena.BookingRequest bookingRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/BookingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/BookingRequestResponse")]
        System.Threading.Tasks.Task<Sirena.BookingResponse> BookingRequestAsync(Sirena.BookingRequest bookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendBookingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendBookingRequestResponse")]
        Sirena.BookingResponse SendBookingRequest(Sirena.BookingRequest bookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendBookingRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendBookingRequestResponse")]
        System.Threading.Tasks.Task<Sirena.BookingResponse> SendBookingRequestAsync(Sirena.BookingRequest bookingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/BookingCancelRequest", ReplyAction="http://tempuri.org/ISirenaGateService/BookingCancelRequestResponse")]
        Sirena.Dto.Responses.BookingCancelResponse BookingCancelRequest([System.ServiceModel.MessageParameterAttribute(Name="bookingCancelRequest")] Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/BookingCancelRequest", ReplyAction="http://tempuri.org/ISirenaGateService/BookingCancelRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.BookingCancelResponse> BookingCancelRequestAsync(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendBookingCancelRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendBookingCancelRequestResponse")]
        Sirena.Dto.Responses.BookingCancelResponse SendBookingCancelRequest(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendBookingCancelRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendBookingCancelRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.BookingCancelResponse> SendBookingCancelRequestAsync(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SellingQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SellingQueryRequestResponse")]
        Sirena.Dto.Responses.SellingQueryResponse SellingQueryRequest([System.ServiceModel.MessageParameterAttribute(Name="sellingQueryRequest")] Sirena.Dto.Requests.SellingQueryRequest sellingQueryRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SellingQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SellingQueryRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.SellingQueryResponse> SellingQueryRequestAsync(Sirena.Dto.Requests.SellingQueryRequest sellingQueryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendSellingQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendSellingQueryRequestResponse")]
        Sirena.Dto.Responses.SellingQueryResponse SendSellingQueryRequest(Sirena.Dto.Requests.SellingQueryRequest bookingCancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendSellingQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendSellingQueryRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.SellingQueryResponse> SendSellingQueryRequestAsync(Sirena.Dto.Requests.SellingQueryRequest bookingCancelRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PaymentExtAuthConfirmRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PaymentExtAuthConfirmRequestResponse")]
        Sirena.Dto.Responses.PaymentExtAuthConfirmResponse PaymentExtAuthConfirmRequest([System.ServiceModel.MessageParameterAttribute(Name="paymentExtAuthConfirmRequest")] Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PaymentExtAuthConfirmRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PaymentExtAuthConfirmRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthConfirmResponse> PaymentExtAuthConfirmRequestAsync(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthConfirmRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthConfirmRequestResponse")]
        Sirena.Dto.Responses.PaymentExtAuthConfirmResponse SendPaymentExtAuthConfirmRequest(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthConfirmRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthConfirmRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthConfirmResponse> SendPaymentExtAuthConfirmRequestAsync(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PaymentExtAuthQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PaymentExtAuthQueryRequestResponse")]
        Sirena.Dto.Responses.PaymentExtAuthQueryResponse PaymentExtAuthQueryRequest([System.ServiceModel.MessageParameterAttribute(Name="paymentExtAuthQueryRequest")] Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/PaymentExtAuthQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/PaymentExtAuthQueryRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthQueryResponse> PaymentExtAuthQueryRequestAsync(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthQueryRequestResponse")]
        Sirena.Dto.Responses.PaymentExtAuthQueryResponse SendPaymentExtAuthQueryRequest(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthQueryRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendPaymentExtAuthQueryRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthQueryResponse> SendPaymentExtAuthQueryRequestAsync(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/GetInitReceiptsRequest", ReplyAction="http://tempuri.org/ISirenaGateService/GetInitReceiptsRequestResponse")]
        Sirena.Dto.Responses.GetItinReceiptsResponse GetInitReceiptsRequest([System.ServiceModel.MessageParameterAttribute(Name="getInitReceiptsRequest")] Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/GetInitReceiptsRequest", ReplyAction="http://tempuri.org/ISirenaGateService/GetInitReceiptsRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.GetItinReceiptsResponse> GetInitReceiptsRequestAsync(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendGetInitReceiptsRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendGetInitReceiptsRequestResponse")]
        Sirena.Dto.Responses.GetItinReceiptsResponse SendGetInitReceiptsRequest(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISirenaGateService/SendGetInitReceiptsRequest", ReplyAction="http://tempuri.org/ISirenaGateService/SendGetInitReceiptsRequestResponse")]
        System.Threading.Tasks.Task<Sirena.Dto.Responses.GetItinReceiptsResponse> SendGetInitReceiptsRequestAsync(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISirenaGateServiceChannel : SirenaSoapClient.SirenaGateServiceReference.ISirenaGateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SirenaGateServiceClient : System.ServiceModel.ClientBase<SirenaSoapClient.SirenaGateServiceReference.ISirenaGateService>, SirenaSoapClient.SirenaGateServiceReference.ISirenaGateService {
        
        public SirenaGateServiceClient() {
        }
        
        public SirenaGateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SirenaGateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirenaGateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SirenaGateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SendStringRequest(string data) {
            return base.Channel.SendStringRequest(data);
        }
        
        public System.Threading.Tasks.Task<string> SendStringRequestAsync(string data) {
            return base.Channel.SendStringRequestAsync(data);
        }
        
        public string StringRequest(string data) {
            return base.Channel.StringRequest(data);
        }
        
        public System.Threading.Tasks.Task<string> StringRequestAsync(string data) {
            return base.Channel.StringRequestAsync(data);
        }
        
        public Sirena.KeyInfoResponse KeyInfoRequest(Sirena.KeyInfoRequest keyInfoRequest1) {
            return base.Channel.KeyInfoRequest(keyInfoRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.KeyInfoResponse> KeyInfoRequestAsync(Sirena.KeyInfoRequest keyInfoRequest) {
            return base.Channel.KeyInfoRequestAsync(keyInfoRequest);
        }
        
        public Sirena.KeyInfoResponse SendKeyInfoRequest(Sirena.KeyInfoRequest keyInfoRequest) {
            return base.Channel.SendKeyInfoRequest(keyInfoRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.KeyInfoResponse> SendKeyInfoRequestAsync(Sirena.KeyInfoRequest keyInfoRequest) {
            return base.Channel.SendKeyInfoRequestAsync(keyInfoRequest);
        }
        
        public Sirena.ScheduleResponse ScheduleRequest(Sirena.ScheduleRequest scheduleRequest1) {
            return base.Channel.ScheduleRequest(scheduleRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.ScheduleResponse> ScheduleRequestAsync(Sirena.ScheduleRequest scheduleRequest) {
            return base.Channel.ScheduleRequestAsync(scheduleRequest);
        }
        
        public Sirena.ScheduleResponse SendScheduleRequest(Sirena.ScheduleRequest scheduleRequest) {
            return base.Channel.SendScheduleRequest(scheduleRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.ScheduleResponse> SendScheduleRequestAsync(Sirena.ScheduleRequest scheduleRequest) {
            return base.Channel.SendScheduleRequestAsync(scheduleRequest);
        }
        
        public Sirena.AvailabilityResponse AvailabilityRequest(Sirena.AvailabilityRequest availabilityRequest1) {
            return base.Channel.AvailabilityRequest(availabilityRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.AvailabilityResponse> AvailabilityRequestAsync(Sirena.AvailabilityRequest availabilityRequest) {
            return base.Channel.AvailabilityRequestAsync(availabilityRequest);
        }
        
        public Sirena.AvailabilityResponse SendAvailabilityRequest(Sirena.AvailabilityRequest availabilityRequest) {
            return base.Channel.SendAvailabilityRequest(availabilityRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.AvailabilityResponse> SendAvailabilityRequestAsync(Sirena.AvailabilityRequest availabilityRequest) {
            return base.Channel.SendAvailabilityRequestAsync(availabilityRequest);
        }
        
        public Sirena.FaresResponse FaresRequest(Sirena.FaresRequest faresRequest1) {
            return base.Channel.FaresRequest(faresRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.FaresResponse> FaresRequestAsync(Sirena.FaresRequest faresRequest) {
            return base.Channel.FaresRequestAsync(faresRequest);
        }
        
        public Sirena.FaresResponse SendFaresRequest(Sirena.FaresRequest faresRequest) {
            return base.Channel.SendFaresRequest(faresRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.FaresResponse> SendFaresRequestAsync(Sirena.FaresRequest faresRequest) {
            return base.Channel.SendFaresRequestAsync(faresRequest);
        }
        
        public Sirena.FareremarkResponse FareremarkRequest(Sirena.FareremarkRequest fareremarkRequest1) {
            return base.Channel.FareremarkRequest(fareremarkRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.FareremarkResponse> FareremarkRequestAsync(Sirena.FareremarkRequest fareremarkRequest) {
            return base.Channel.FareremarkRequestAsync(fareremarkRequest);
        }
        
        public Sirena.FareremarkResponse SendFareremarkRequest(Sirena.FareremarkRequest fareremarkRequest) {
            return base.Channel.SendFareremarkRequest(fareremarkRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.FareremarkResponse> SendFareremarkRequestAsync(Sirena.FareremarkRequest fareremarkRequest) {
            return base.Channel.SendFareremarkRequestAsync(fareremarkRequest);
        }
        
        public Sirena.Dto.Responses.PricingResponse PricingRequest(Sirena.Dto.Requests.PricingRequest pricingRequest1) {
            return base.Channel.PricingRequest(pricingRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PricingResponse> PricingRequestAsync(Sirena.Dto.Requests.PricingRequest pricingRequest) {
            return base.Channel.PricingRequestAsync(pricingRequest);
        }
        
        public Sirena.Dto.Responses.PricingResponse SendPricingRequest(Sirena.Dto.Requests.PricingRequest pricingRequest) {
            return base.Channel.SendPricingRequest(pricingRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PricingResponse> SendPricingRequestAsync(Sirena.Dto.Requests.PricingRequest pricingRequest) {
            return base.Channel.SendPricingRequestAsync(pricingRequest);
        }
        
        public Sirena.Dto.Responses.DescribeResponse DescribeRequest(Sirena.Dto.Requests.DescribeRequest describeRequest1) {
            return base.Channel.DescribeRequest(describeRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.DescribeResponse> DescribeRequestAsync(Sirena.Dto.Requests.DescribeRequest describeRequest) {
            return base.Channel.DescribeRequestAsync(describeRequest);
        }
        
        public Sirena.Dto.Responses.DescribeResponse SendDescribeRequest(Sirena.Dto.Requests.DescribeRequest describeRequest) {
            return base.Channel.SendDescribeRequest(describeRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.DescribeResponse> SendDescribeRequestAsync(Sirena.Dto.Requests.DescribeRequest describeRequest) {
            return base.Channel.SendDescribeRequestAsync(describeRequest);
        }
        
        public Sirena.BookingResponse BookingRequest(Sirena.BookingRequest bookingRequest1) {
            return base.Channel.BookingRequest(bookingRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.BookingResponse> BookingRequestAsync(Sirena.BookingRequest bookingRequest) {
            return base.Channel.BookingRequestAsync(bookingRequest);
        }
        
        public Sirena.BookingResponse SendBookingRequest(Sirena.BookingRequest bookingRequest) {
            return base.Channel.SendBookingRequest(bookingRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.BookingResponse> SendBookingRequestAsync(Sirena.BookingRequest bookingRequest) {
            return base.Channel.SendBookingRequestAsync(bookingRequest);
        }
        
        public Sirena.Dto.Responses.BookingCancelResponse BookingCancelRequest(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest1) {
            return base.Channel.BookingCancelRequest(bookingCancelRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.BookingCancelResponse> BookingCancelRequestAsync(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest) {
            return base.Channel.BookingCancelRequestAsync(bookingCancelRequest);
        }
        
        public Sirena.Dto.Responses.BookingCancelResponse SendBookingCancelRequest(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest) {
            return base.Channel.SendBookingCancelRequest(bookingCancelRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.BookingCancelResponse> SendBookingCancelRequestAsync(Sirena.Dto.Requests.BookingCancelRequest bookingCancelRequest) {
            return base.Channel.SendBookingCancelRequestAsync(bookingCancelRequest);
        }
        
        public Sirena.Dto.Responses.SellingQueryResponse SellingQueryRequest(Sirena.Dto.Requests.SellingQueryRequest sellingQueryRequest1) {
            return base.Channel.SellingQueryRequest(sellingQueryRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.SellingQueryResponse> SellingQueryRequestAsync(Sirena.Dto.Requests.SellingQueryRequest sellingQueryRequest) {
            return base.Channel.SellingQueryRequestAsync(sellingQueryRequest);
        }
        
        public Sirena.Dto.Responses.SellingQueryResponse SendSellingQueryRequest(Sirena.Dto.Requests.SellingQueryRequest bookingCancelRequest) {
            return base.Channel.SendSellingQueryRequest(bookingCancelRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.SellingQueryResponse> SendSellingQueryRequestAsync(Sirena.Dto.Requests.SellingQueryRequest bookingCancelRequest) {
            return base.Channel.SendSellingQueryRequestAsync(bookingCancelRequest);
        }
        
        public Sirena.Dto.Responses.PaymentExtAuthConfirmResponse PaymentExtAuthConfirmRequest(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest1) {
            return base.Channel.PaymentExtAuthConfirmRequest(paymentExtAuthConfirmRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthConfirmResponse> PaymentExtAuthConfirmRequestAsync(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest) {
            return base.Channel.PaymentExtAuthConfirmRequestAsync(paymentExtAuthConfirmRequest);
        }
        
        public Sirena.Dto.Responses.PaymentExtAuthConfirmResponse SendPaymentExtAuthConfirmRequest(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest) {
            return base.Channel.SendPaymentExtAuthConfirmRequest(paymentExtAuthConfirmRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthConfirmResponse> SendPaymentExtAuthConfirmRequestAsync(Sirena.Dto.Requests.PaymentExtAuthConfirmRequest paymentExtAuthConfirmRequest) {
            return base.Channel.SendPaymentExtAuthConfirmRequestAsync(paymentExtAuthConfirmRequest);
        }
        
        public Sirena.Dto.Responses.PaymentExtAuthQueryResponse PaymentExtAuthQueryRequest(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest1) {
            return base.Channel.PaymentExtAuthQueryRequest(paymentExtAuthQueryRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthQueryResponse> PaymentExtAuthQueryRequestAsync(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest) {
            return base.Channel.PaymentExtAuthQueryRequestAsync(paymentExtAuthQueryRequest);
        }
        
        public Sirena.Dto.Responses.PaymentExtAuthQueryResponse SendPaymentExtAuthQueryRequest(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest) {
            return base.Channel.SendPaymentExtAuthQueryRequest(paymentExtAuthQueryRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.PaymentExtAuthQueryResponse> SendPaymentExtAuthQueryRequestAsync(Sirena.Dto.Requests.PaymentExtAuthQueryRequest paymentExtAuthQueryRequest) {
            return base.Channel.SendPaymentExtAuthQueryRequestAsync(paymentExtAuthQueryRequest);
        }
        
        public Sirena.Dto.Responses.GetItinReceiptsResponse GetInitReceiptsRequest(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest1) {
            return base.Channel.GetInitReceiptsRequest(getInitReceiptsRequest1);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.GetItinReceiptsResponse> GetInitReceiptsRequestAsync(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest) {
            return base.Channel.GetInitReceiptsRequestAsync(getInitReceiptsRequest);
        }
        
        public Sirena.Dto.Responses.GetItinReceiptsResponse SendGetInitReceiptsRequest(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest) {
            return base.Channel.SendGetInitReceiptsRequest(getInitReceiptsRequest);
        }
        
        public System.Threading.Tasks.Task<Sirena.Dto.Responses.GetItinReceiptsResponse> SendGetInitReceiptsRequestAsync(Sirena.Dto.Requests.GetInitReceiptsRequest getInitReceiptsRequest) {
            return base.Channel.SendGetInitReceiptsRequestAsync(getInitReceiptsRequest);
        }
    }
}
